### ISSUE TITLE
Works nicely, but not as documented

### ISSUE THREAD

**Issue by jijoel** [T-Regx/CrossDataProviders#1]
Nice package! I tried running it as documented, with:

```php
/**
 * @test
 * @dataProviders getSearchParameters
 */
public function users_can_search_for_booking($role, $field)
{
    dump($role, $field);
}

public function getSearchParameters()
{
    return DataProviders::cross(
        [ ['admin'], ['partner'], ['user'], ],
        [ ['title'], ['email'], ['city'], ['state'], ['description'], ]
    );
}}
```

That did not work for me. What did work was using the CrossDataProviders directly, like this:

```php
/**
 * @test
 * @dataProvider getSearchParameters    // NOTE: using @dataProvider here, not @dataProviders
 */
public function users_can_search_for_booking($role, $field)
{
    dump($role, $field);
}

public function getSearchParameters()
{
    return CrossDataProviders::cross(
        [ ['admin'], ['partner'], ['user'], ],
        [ ['title'], ['email'], ['city'], ['state'], ['description'], ]
    );
}
```

**Comment by Danon** [comment]
Hey, thank you for using the lib! 🗡 

Of course, it was supposed to be `@ dataProvider`. My typo in the documentation, I already corrected it :)

**Comment by Danon** [comment]
As to the method name, you are right about that too! :D 

As you sait, it's either:
 - `CrossDataProviders::cross()`
 - `DataProviders::crossAll()`

I'll update the documentation to be more throughout today evening (around 21:00-22:00). Thanks for finding it :)

For now, if you need insight - you can check out my unit tests:
 -  https://github.com/T-Regx/CrossDataProviders/blob/master/test/TRegx/CrossData/DataProvidersTest.php
 - https://github.com/T-Regx/CrossDataProviders/blob/master/test/TRegx/CrossData/CrossDataProvidersTest.php
