### ISSUE TITLE
Flatten und standardify the directory structure

### ISSUE THREAD

**Issue by oliverklee** [T-Regx/CrossDataProviders#26]
I'd like to flatten the directory structure like this:
- `src/TRegx/DataProvider/*.php` -> `src/*.php`
- `test/TRegx/DataProvider/*.php` -> `tests/*.php`

So basically, I'd like to drop the empty in-between structure `TRegx/DataProvider` (without changing the PHP namespaces of the classes) and rename `test/` to `tests/` to be more in sync what most other PHP projects use.

@Danon Would you be okay with this?

**Comment by Danon** [comment]
With the flatten of the namespace, sure. 

With the rename of the `test/`, not so much. I don't really use plurar forms in any of the namespaces and folders.
